parameters:
    kuborgh_csv.parser.simple.class: Kuborgh\CsvBundle\Parser\SimpleParser
    kuborgh_csv.parser.character.class: Kuborgh\CsvBundle\Parser\CharacterParser
    kuborgh_csv.configuration.parser.class: Kuborgh\CsvBundle\Configuration\ParserConfiguration
